
name: COBOL Check Automation

on:
  workflow_dispatch:

jobs:
  mainframe-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install SSH tools
        run: sudo apt-get install -y sshpass
      
      - name: Create Base Directory
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "mkdir -p /z/${{ secrets.SSH_USERNAME }}/cobolcheck"
      
      - name: Upload Entire src Folder
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r \
            ./src \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/z/${{ secrets.SSH_USERNAME }}/cobolcheck/
      
      - name: Verify Upload
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "ls -laR /z/${{ secrets.SSH_USERNAME }}/cobolcheck"
